### ISSUE TITLE
Stop button to stop sending messages

### ISSUE THREAD

**Issue by shizn** [Azure-Samples/raspberry-pi-web-simulator#11]
I was not able to stop this without closing the browser tab. I could be just not sure of what to do so apologies if there is an obvious thing I am missing. As an FYI I wanted the stop button because as I was working step by step through the tutorials I monitored the overview in Azure IoT message count. I would have liked to started the service and check the number of messages received - stop it check again then restart. Just a real basic check to see if it was working as I expected.

**Comment by michaeljqzq** [comment]
We'll add this feature.

**Comment by michaeljqzq** [comment]
Feature added in aa263537752fae4139062a5a394493e1349c214d 
will deploy in this week

**Comment by michaeljqzq** [comment]
Deployed to prod.
