### ISSUE TITLE
Bug with BlinkLED

### ISSUE THREAD

**Issue by sideye** [Azure-Samples/raspberry-pi-web-simulator#15]
When the send message interval time is shorter than the blink LED time, the LED blink time does not follow the desired blink LED time in the blink LED method.

**Comment by michaeljqzq** [comment]
Hi @sideye , thanks for your feedback. The issue has been confirmed. We'll fix and deploy in the next deployment cycle.

**Comment by michaeljqzq** [comment]
already fixed and deployed to prod
