### ISSUE TITLE
Test site

### ISSUE THREAD

**Issue by IgorGanapolsky** [Azure-Samples/raspberry-pi-web-simulator#32]
Hi,
your README says to check changes on test site.  However, it is a proprietary site that has a login account.  Is this meant for contributors to look at?

Thank you,
Igor

**Comment by michaeljqzq** [comment]
Hi @IgorGanapolsky , every commit on source branch will trigger a build and deploy on the test site. In order no to be indexed by search engines, we add a basic authentication on the test site. We will provide the username/password for contributors if they would like to review the change on the test site.
