### ISSUE TITLE
"Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by timh45** [Azure-Samples/raspberry-pi-web-simulator#38]
Guys, the sim was working for me yesterday fine. But since then I keep getting:

"Cannot read property 'length' of undefined"

I've tried a variety of browsers (Safari/Chrome), deleted cookies, run in-private but to no avail.

Any ideas? I see @michaeljqzq did a commit yesterday?

**Comment by michaeljqzq** [comment]
@timh45 , one of the dependency packages causes the break. We just rolled back to the last version. Please try again. If still found the issue, try to clear the browser cache (Chrome: F12 -> right click refresh button -> Empty cache and hard reload)

**Comment by timh45** [comment]
Beautiful! That's fixed it. Thanks @michaeljqzq you're a star. I need to get on with some tutorials dependant on the sim. Cheers!

**Comment by michaeljqzq** [comment]
@timh45 My pleasure
