### ISSUE TITLE
Not working for Edge

### ISSUE THREAD

**Issue by kentstroker** [Azure-Samples/raspberry-pi-web-simulator#5]
The connect string when copied and pasted from IoT Hub is missing the DeviceID. No docs on how to add a DeviceID and I tried it in every position within the connection string to no avail.

Second, there is no LEDPin defined and it should be right after the const connectString entry but is missing.

**Comment by shizn** [comment]
@kentstroker  thanks for submitting the issue. I need a screen shot to reproduce the first issue from my side. For the second issue, actually, you can see in Line16 const LEDPin = 4 in the default sample.

**Comment by shizn** [comment]
The browser is Edge here. For Edge. The LED does not always flash on the simulation.
![image](https://cloud.githubusercontent.com/assets/3619378/26769529/3f78e688-49e2-11e7-876a-67b4116cc1ab.png)

**Comment by michaeljqzq** [comment]
Hi @kentstroker , about your first question, you can copy the connection string of a device in this way:
<img width="913" alt="connectionstringinportal" src="https://user-images.githubusercontent.com/9349786/26916670-cffd8470-4c5d-11e7-9c7d-38ce9e50934b.png">
Also we will add this help information to the site soon.
